---
version: 1.3
workflows:
   - name: rna-seq-pipeline-per-sample
     publish: True
     subclass: WDL
     primaryDescriptorPath: /rna-seq-pipeline-per-sample.wdl
     authors:
       - name: Tsuyoshi Hachiya
         orcid: https://orcid.org/0000-0002-5274-3266
